### ISSUE TITLE
installation guide

### ISSUE THREAD

**Issue by codecheffy** [jearbear/dotfiles#1]
could you create an installation guide? with necessary dependencies and such?

**Comment by jearbear** [comment]
Hey sorry, didn't notice this until now! I've updated the readme a bit, you just need gnu-stow. You can just do `stow neovim` for example and it will link to your home directory. Here's a good article on it: http://brandon.invergo.net/news/2012-05-26-using-gnu-stow-to-manage-your-dotfiles.html
